const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
const GET_LIST_ERROR = 'GET_LIST_ERROR';
const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export {
  GET_LIST_REQUEST,
  GET_LIST_SUCCESS,
  GET_LIST_ERROR,
  ADD_PRODUCT_REQUEST,
  REMOVE_PRODUCT_REQUEST
};